apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: terraform
    namespace: blog-posts
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
