apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-role
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argocd
  name: argocd-role-binding
subjects:
  - kind: ServiceAccount
    name: terraform
    namespace: argocd
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
